Bianca
chingu-voyages/v46-tier3-team-35 pull request #29
Opened 2023-10-27 20:25 UTC by siasktv

Landing Page & Navbar

2023-10-29 22:20 UTC, keldim commented on client/dummy-crypto-data/marketTrendsCrypto.js
hey bianca, where is this file being used?
would it be okay to delete it if it is not being used?

2023-10-29 22:46 UTC, keldim commented on client/assets/Logo.png
hey bianca, I think it is better to put the 'assets', 'data', 'dummy-crypto-data' folders inside the 'src' folder
just to be safe
https://stackoverflow.com/questions/44643041/do-i-store-image-assets-in-public-or-src-in-reactjs

2023-10-29 23:13 UTC, yi-lin-1234 approved these changes
worked as expected

2023-10-29 23:38 UTC, keldim requested changes
left comments in the code

2023-11-02 21:01 UTC, siasktv commented on client/dummy-crypto-data/marketTrendsCrypto.js
yes, it can be delete it

2023-11-02 21:01 UTC, siasktv commented on client/assets/Logo.png
sure!

2023-11-03 06:41 UTC, keldim approved these changes

2023-11-03 06:43 UTC, merged